#![feature(portable_simd, iter_array_chunks, array_chunks)]
pub mod blake;
pub mod docs_component;
pub mod docs_component_piotrek;
pub mod docs_component_proper;
pub mod new_example;
pub mod plonk;
pub mod poseidon;
pub mod poseidon_custom;
pub mod poseidon_uacias;
pub mod poseidon_u_components;
pub mod poseidon_optimized;
pub mod scheduler_poseidon;
pub mod state_machine;
pub mod wide_fibonacci;
pub mod xor;
