[package]
name = "air_utils"
version.workspace = true
edition.workspace = true

[features]
# parallel = ["rayon"]

[dependencies]
# rayon = { version = "1.10.0", optional = false }
bytemuck.workspace = true
itertools.workspace = true
rayon = { version = "1.10.0", optional = false }
stwo-prover = { path = "../prover" }

