[package]
name = "stwo-compact-binary"
version.workspace = true
edition.workspace = true

[features]
default = ["std"]
std = [
    "std-shims/std",
]

[dependencies]
starknet-ff = { version = "0.3.7", default-features = false, features = [
    "alloc",
    "serde",
] }
unsigned-varint.workspace = true
lz4_flex = { version = "0.11", default-features = false }
std-shims.workspace = true

[lib]
bench = false
