name: Benchmarks Pages

on:
  push:
    branches:
      - dev

permissions:
  # deployments permission to deploy GitHub pages website
  deployments: write
  # contents permission to update benchmark contents in gh-pages branch
  contents: write

jobs:
  run-avx-bench:
    runs-on: namespace-profile-starkware-libs-stwo-large-ubuntu-24-04-amd64
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: ./.github/actions/bootstrap_runners
      - uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c # master
        with:
          toolchain: nightly-2026-01-15
      - name: Detect benchmark environment
        id: benchmark_environment
        run: |
          cpu_model=$(lscpu | sed -n 's/^Model name:[[:space:]]*//p' | head -n 1)
          echo "cpu_model=${cpu_model}" >> "$GITHUB_OUTPUT"
      - name: Run benchmark
        run: |
          cargo install cargo-criterion
          ./scripts/bench.sh |& tee output.txt
      - name: Download previous benchmark data
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ./cache
          key: ${{ runner.os }}-${{github.event.pull_request.base.ref}}-benchmark
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@52576c92bccf6ac60c8223ec7eb2565637cae9ba # v1
        with:
          name: Stwo (${{ steps.benchmark_environment.outputs.cpu_model }}, single-threaded)
          tool: "cargo"
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
